name: main

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MSYS, cc: gcc, cxx: g++, fc: gfortran },
        ]

    name: ${{ matrix.msystem }}-${{ matrix.cc }}
    runs-on: windows-2022
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      FC: ${{ matrix.fc }}
    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        if: ${{ matrix.msystem != 'MSYS' }}
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            ${{ matrix.prefix }}-meson
            ${{ matrix.prefix }}-ninja
            ${{ matrix.prefix }}-cmake
            ${{ matrix.prefix }}-make
            ${{ matrix.prefix }}-${{ matrix.cc == 'gcc' && 'gcc-ada' || 'ninja'}}
            ${{ matrix.prefix }}-${{ matrix.cc != 'gcc' && 'openmp' || 'ninja'}}
            ${{ matrix.prefix }}-${{ matrix.cc != 'gcc' && 'lld' || 'ninja'}}
            ${{ matrix.prefix }}-${{ matrix.cc != 'gcc' && 'libc++' || 'ninja'}}
            ${{ matrix.prefix }}-${{ matrix.fc == 'gfortran' && 'gcc-fortran' || 'ninja'}}
            ${{ matrix.prefix }}-${{ matrix.fc == 'flang' && 'flang' || 'ninja'}}
            ${{ matrix.prefix }}-${{ matrix.cc }}
            ${{ matrix.prefix }}-python
            ${{ matrix.prefix }}-python-setuptools
            ${{ matrix.prefix }}-autotools
            ${{ matrix.prefix }}-perl
            ${{ matrix.prefix }}-gdb
            make
            git

      - uses: msys2/setup-msys2@v2
        if: ${{ matrix.msystem == 'MSYS' }}
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            meson
            ninja
            cmake
            make
            gcc
            python
            python-setuptools
            autotools
            ruby
            perl
            mingw-w64-cross-gcc
            gdb
            git

      - name: Add staging repo
        shell: msys2 {0}
        run: |
          sed -i '1s|^|[staging]\nServer = https://repo.msys2.org/staging/\nSigLevel = Never\n|' /etc/pacman.conf

      - name: Update using staging
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'

      - name: "test: runtime"
        shell: msys2 {0}
        run: |
          make -j runtime
